class City:
	@staticmethod
	def install_tables(db) -> None:
		with db.cursor() as cur:
			cur.execute("""
				create table if not exists city
				(
					id int generated by default as identity,
					x int,
					y int,
					city_name text,
					city_level int,
					list_order int,
					population int,
					max_population int,
					satisfaction int,
					action_points_available int
				);
			""")

	@staticmethod
	def install_indexes(db) -> None:
		with db.cursor() as cur:
			cur.execute("""
				create index if not exists city_x on city(x);
				create index if not exists city_y on city(y);
				create index if not exists city_city_name on city(city_name);
				create index if not exists city_list_order on city(list_order);
			""")

	@staticmethod
	def install_pg_functions(db) -> None:
		with db.cursor() as cur:
			pass  # cur.execute()
